INSERT INTO `questiontable` VALUES (0, 'What is the capital city of Saudi Arabia?', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `questiontable` VALUES (1, 'In which year did the Titanic sink?', '1892', '1898', '1908', '1912', 'D');
INSERT INTO `questiontable` VALUES (2, 'In which year did the demolition of the Berlin Wall begin?', '1986', '1989', '1991', '1993', 'B');
INSERT INTO `questiontable` VALUES (3, 'Who saw his crew dine on wormy biscuits and rats on his fourth voyage to the New World?\"', 'Christopher Columbus', 'Vasco de Gama', 'Marco Polo', 'Americo Vespucci ', 'A');
INSERT INTO `questiontable` VALUES (4, ' that gave Russia control of the Black Sea?', 'Great Britain', 'Austria-Hungary Empire ', 'Ottoman Empire', 'Holy Roman Empire', 'C');
INSERT INTO `questiontable` VALUES (5, 'What nationality was Karl Marx?', 'French', 'Dannish', 'Swiss', 'German', 'D');
INSERT INTO `questiontable` VALUES (6, 'Which treaty finished the Turkish Independence War? ', 'Loussane Peace Treaty', 'Sevres Peace Treaty ', 'Mudanya Truce', 'Mondros Truce', 'C');
INSERT INTO `questiontable` VALUES (7, 'In which year was the Wall Street Crash?', '1923', '1929', '1933', '1939', 'B');
INSERT INTO `questiontable` VALUES (8, 'Who invented the telescope ?', 'Leonardo Da Vinci', 'Nicolaus Copernecus', 'Johannes Kepler', 'Galileo Galilei', 'D');
INSERT INTO `questiontable` VALUES (9, 'For which of the following disciplines is Nobel Prize awarded?', 'Physics and Chemistry', 'Physiology or Medicine', 'Literature, Peace and Economics', 'All of the above', 'D');
INSERT INTO `questiontable` VALUES (10, 'In Roman mythology, Neptune is the equivalent to which Greek god?', 'Zeus', 'Poseidon', 'Hades', 'Apollon', 'B');
INSERT INTO `questiontable` VALUES (11, 'Which American state is nearest to the Russian Federation?', 'Nebraska', 'Wyoming', 'Delaware', 'Alaska', 'D');
INSERT INTO `questiontable` VALUES (12, 'In which year, terrorists crash two planes into New York\'s World Trade Centre on September 11 in a sequence of destruction?', '1999', '2000', '2001', '2002', 'C');
INSERT INTO `questiontable` VALUES (13, 'What is the official language of Andorra?', 'Spanish', 'French', 'Catalan', 'Basque', 'C');
INSERT INTO `questiontable` VALUES (15, 'How many times has Brazil won the World Cup Football Championship?', '3', '4', '5', '6', 'C');
INSERT INTO `questiontable` VALUES (16, 'In terms of area, which island is the largest in the Mediterranean Sea?', 'Crete', 'Sicily', 'Malta', 'Cyprus', 'B');
INSERT INTO `questiontable` VALUES (17, 'Instrument used to measure earthquake is known as:', 'Seismograph', 'Quake meter', 'Barometer', 'None of the above', 'A');
INSERT INTO `questiontable` VALUES (18, 'Which one of the following zones of the atmosphere is rich in Ozone gas?', 'Mesosphere', 'Stratosphere', 'Troposphere', 'Ionosphere', 'B');
INSERT INTO `questiontable` VALUES (19, 'What is the name of the capital city of Australia?', 'Sydney', 'Melbourne', 'Canberra', 'Adelaide', 'C');
INSERT INTO `questiontable` VALUES (20, 'Troposphere is the hottest part of the atmosphere because...', 'it is closest to the sun', 'it is heated by the Earth\'s surface', 'heat is generated in it', 'there are charged particles in it', 'B');
INSERT INTO `questiontable` VALUES (21, 'Which of the following do not belong to solar system?', 'Asteroids', 'Comets', 'Planets', 'Nebulae', 'D');
INSERT INTO `questiontable` VALUES (22, 'We always see the same face of the Moon becasue...', 'it is smaller than earth ', 'it revolves on its axis in the direction opposite to that of the earth', 'it takes equal time for revolution around the earth and rotation on its own axis', 'it rotates at the same speed as the earth around the sun', 'C');
INSERT INTO `questiontable` VALUES (23, 'Which imaginary line, located at zero degrees latitude,divides the earth into Northern and Southern hemispheres?', 'Equator', 'Horizontal', 'Vertical', 'None of the above', 'A');
INSERT INTO `questiontable` VALUES (24, 'When a body is taken from the earth to the moon:', 'Its weight increases', 'Its weight remains unchanged', 'It becomes completely weightless', 'Its weight decreases', 'D');
INSERT INTO `questiontable` VALUES (25, 'What so-called war spawned the dueling slogans Better Dead Than RED and Better Red Than Dead in the 1950\'s?', 'World War II', 'Korean War', 'Vietnam War', 'Cold War', 'D');
INSERT INTO `questiontable` VALUES (26, 'Where is the world\'s largest soccer stadium?', 'Spain', 'Brazil', 'Germany', 'China', 'B');
INSERT INTO `questiontable` VALUES (27, 'Who said, \'\'I think, therefore I am?\'\' ', 'Descartes', 'Aristotle', 'Plato', 'Archimedes', 'A');
INSERT INTO `questiontable` VALUES (28, 'In what country the world\'s first water clock was invented?', 'Rome', 'Egypt', 'China', 'Persia', 'B');
INSERT INTO `questiontable` VALUES (29, 'What was the first James Bond book?', 'Goldfinger', 'Casino Royale', 'Diamonds are forever', 'Live and Let Die', 'B');
INSERT INTO `questiontable` VALUES (30, 'What was Al Capone\'s father\'s occupation?', 'Butcher', 'Salesman', 'Doctor', 'Barber', 'D');
INSERT INTO `questiontable` VALUES (31, 'Most popes have been Italian. Which country has the 2nd highest number of Popes?', 'England', 'Greece', 'France', 'Spain', 'C');
INSERT INTO `questiontable` VALUES (32, 'Which classic novel sold only fifty copies during the authors lifetime?', 'Moby Dick', 'Robin Hood', 'Animal Farm', 'Oliver Twist', 'A');
INSERT INTO `questiontable` VALUES (33, 'Who has been Pope the longest in the 20th century?', 'Pope Fracis II', 'Pope John Paul I', 'Pope Benedict XVI', 'Pope St. John Paul II', 'D');
INSERT INTO `questiontable` VALUES (34, 'Which middle name did UK Prime Minister Winston Churchill share with Charlie Chaplin?', 'Spencer', 'Chuck', 'Philip', 'Edmund', 'A');
INSERT INTO `questiontable` VALUES (35, 'Which capital city has the fewest cinemas in relation to its population?', 'Pyongyang', 'Tehran', 'Cairo', 'Kabul', 'C');
INSERT INTO `questiontable` VALUES (36, 'According to the Aetherius Society, who is alive and living on Venus?', 'Zeus', 'Jesus Christ', 'Buddha', 'Thor', 'B');
INSERT INTO `questiontable` VALUES (37, 'The name Chicago comes from a native Indian word that means what?', 'Place that have lots of gold', 'Place of gathering ', 'Place of bull\'s horns', 'Place that smells bad', 'D');
INSERT INTO `questiontable` VALUES (38, 'There are more what  in Los Angeles than in all France?', 'Directors', 'Judges', 'Brokers', 'Spacemen', 'B');
INSERT INTO `questiontable` VALUES (39, 'Fifty six percent of Americans believe there is what in heaven?', 'Baseball', 'Hamburger', 'Hot Dog', 'Football', 'A');
INSERT INTO `questiontable` VALUES (40, 'What country has the most daily newspapers in the world?', 'United Kingdom', 'Japan', 'India', 'China', 'D');
